import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AddPublicKey from "../components/AddPublicKey";
import ConnectMetamask from "../components/ConnectMetamask";
import EncryptData from "../components/EncryptData";
import TestDecrypt from "../components/TestDecrypt";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "2rem",
            minWidth: "600px",
          }}
        >
          <div style={{ display: "flex" }}>
            <ConnectMetamask />
          </div>

          <AddPublicKey />

          <EncryptData />

          <TestDecrypt />
        </div>
      </main>
    </div>
  );
};

export default Home;
