import { useMetaMask } from "metamask-react";
import type { NextPage } from "next";
import Head from "next/head";
import { gql } from "urql";
import { useMyMessagesQuery, usePublicKeysQuery } from "../codegen/subgraph";
import AddPublicKey from "../components/AddPublicKey";
import ConnectMetamask from "../components/ConnectMetamask";
import EncryptData from "../components/EncryptData";
import MessageList from "../components/MessageList";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { account } = useMetaMask();
  const [publicKeys] = usePublicKeysQuery();

  const keyAlreadyAdded =
    account &&
    publicKeys.data?.persons.find(
      (p) => p.address.toLowerCase() === account.toLocaleLowerCase()
    ) != null;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-row-reverse">
        <ConnectMetamask />
      </div>

      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "2rem",
            minWidth: "600px",
          }}
        >
          {keyAlreadyAdded ? (
            <>
              <EncryptData />

              <MessageList />
            </>
          ) : (
            <AddPublicKey />
          )}

          {/* <TestDecrypt /> */}
        </div>
      </main>
    </div>
  );
};

export default Home;
