/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface PublicKeyRegistryInterface extends utils.Interface {
  functions: {
    "addPublicKey(bytes32)": FunctionFragment;
    "getPublicKey(address)": FunctionFragment;
    "publicKeys(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addPublicKey" | "getPublicKey" | "publicKeys"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addPublicKey",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicKey",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "publicKeys",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publicKeys", data: BytesLike): Result;

  events: {
    "PublicKeyRegistered(address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PublicKeyRegistered"): EventFragment;
}

export interface PublicKeyRegisteredEventObject {
  account: string;
  publicKey: string;
}
export type PublicKeyRegisteredEvent = TypedEvent<
  [string, string],
  PublicKeyRegisteredEventObject
>;

export type PublicKeyRegisteredEventFilter =
  TypedEventFilter<PublicKeyRegisteredEvent>;

export interface PublicKeyRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PublicKeyRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addPublicKey(
      key: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getPublicKey(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    publicKeys(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addPublicKey(
    key: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getPublicKey(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  publicKeys(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addPublicKey(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getPublicKey(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    publicKeys(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "PublicKeyRegistered(address,bytes32)"(
      account?: PromiseOrValue<string> | null,
      publicKey?: null
    ): PublicKeyRegisteredEventFilter;
    PublicKeyRegistered(
      account?: PromiseOrValue<string> | null,
      publicKey?: null
    ): PublicKeyRegisteredEventFilter;
  };

  estimateGas: {
    addPublicKey(
      key: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getPublicKey(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publicKeys(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPublicKey(
      key: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getPublicKey(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicKeys(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
